# Generated by Django 5.0.4 on 2024-04-14 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework_app02', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='number',
            new_name='phone',
        ),
    ]
