# Generated by Django 5.0.4 on 2024-04-14 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework_app02', '0002_rename_number_client_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='count',
            new_name='quantity',
        ),
    ]
