# Generated by Django 5.0.4 on 2024-04-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework_app02', '0003_rename_count_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default image', upload_to=''),
            preserve_default=False,
        ),
    ]
